import type { Algorithm } from "../types/algorithm";

export const mockAlgorithms: Algorithm[] = [
  {
    id: "gaussiancopula",
    name: "GaussianCopula",
    libraries: ["SDV"],
    category: "copula",
    supported_data: ["single_table"],
    tags: ["高速", "安定", "解釈可能"],
    use_cases: ["テストデータ生成", "統計分析用ダミーデータ"],
    input_requirements: ["カテゴリ対応", "欠損値対応"],
    privacy_mechanism: "none",
    privacy_risk_level: "low",
    description: "コピュラベースの統計的手法",
    strengths: ["高速", "安定"],
    weaknesses: ["非線形関係の再現が弱い"],
    reference: "https://sdv.dev",
    experiments: [
      {
        id: "sdv_gaussiancopula",
        library: "SDV",
        library_version: "1.35.1",
        params: {},
        dataset: "adult",
        data_type: "single_table",
        phase: "phase1",
        metrics: {
          quality_score: 0.8168,
          diagnostic_score: 1.0,
          tstr_accuracy: 0.7563,
          tstr_f1: 0.6555,
          dcr_mean: 0.533,
          dcr_5th_percentile: 0.2239,
          exact_match_rate: 0.0,
          time_sec: 5.94,
        },
      },
    ],
    summary_metrics: {
      best_quality_score: 0.8168,
      best_tstr_f1: 0.6555,
      best_dcr_mean: 0.533,
      fastest_time_sec: 5.94,
    },
  },
  {
    id: "ctgan",
    name: "CTGAN",
    libraries: ["SDV", "SynthCity", "ydata"],
    category: "gan",
    supported_data: ["single_table"],
    tags: ["深層学習", "カテゴリ変数対応"],
    use_cases: ["マスターデータ匿名化", "データ拡張"],
    input_requirements: ["カテゴリ対応"],
    privacy_risk_level: "medium",
    description: "Conditional Tabular GAN",
    strengths: ["複雑な分布を再現"],
    weaknesses: ["学習に時間がかかる", "モード崩壊"],
    experiments: [
      {
        id: "sdv_ctgan_100ep",
        library: "SDV",
        params: { epochs: 100 },
        dataset: "adult",
        data_type: "single_table",
        phase: "phase1",
        metrics: {
          quality_score: 0.86,
          tstr_accuracy: 0.819,
          tstr_f1: 0.8203,
          dcr_mean: 0.3438,
          time_sec: 325.24,
        },
      },
      {
        id: "sdv_ctgan_10ep",
        library: "SDV",
        params: { epochs: 10 },
        dataset: "adult",
        data_type: "single_table",
        phase: "phase1",
        metrics: {
          quality_score: 0.7493,
          tstr_f1: 0.6555,
          dcr_mean: 0.4265,
          time_sec: 241.7,
        },
      },
    ],
    summary_metrics: {
      best_quality_score: 0.86,
      best_tstr_f1: 0.8203,
      best_dcr_mean: 0.4265,
      fastest_time_sec: 241.7,
    },
  },
  {
    id: "bayesian_network",
    name: "BayesianNetwork",
    libraries: ["SynthCity"],
    category: "bayesian",
    supported_data: ["single_table"],
    tags: ["確率モデル", "解釈可能"],
    use_cases: ["研究用"],
    input_requirements: ["カテゴリ対応", "欠損値対応"],
    privacy_risk_level: "high",
    description: "ベイジアンネットワーク",
    strengths: ["TSTR が高い"],
    weaknesses: ["プライバシーリスクが高い"],
    experiments: [],
    summary_metrics: {
      best_quality_score: 0.8263,
      best_tstr_f1: 0.8591,
      best_dcr_mean: 0.2193,
      fastest_time_sec: 220.37,
    },
  },
];
